name: DeAltHDR_dual_encoder_mixed_training
model_type: DeAltHDRModel
scale: 1
num_gpu: 1
manual_seed: 10
n_sequence: 5 # n_frames for T-2,T-1,T,T+1,T+2
dir_data: ['/hdd2/wrl/zsh/cropped_patches_day/train/']
n_colors: 3
rgb_range: 1
no_augment: False
loss_type: 1*L1
patch_size: 192
size_must_mode: 4
model: dealthdr_arch

# DeAltHDR specific parameters
use_dual_encoder: True
training_mode: mixed  # 'optical_flow', 'attention', 'mixed'
num_frames_tocache: 4  # T-2,T-1,T+1,T+2
sensitivity: 15.0  # Default sensitivity parameter for FGMA (s=15 for balanced mode)

pretrain_models_dir: None
type: deblurring
dim: 64
Enc_blocks: [2, 6, 10]
Middle_blocks: 11
Dec_blocks: [10, 6, 2]
num_refinement_blocks: 2
use_both_input: False
num_heads: [1, 2, 4, 8]
ffn_expansion_factor: 2.5

# Encoder attention types
encoder1_attn_type1 : "ReducedAttn"
encoder1_attn_type2 : "ReducedAttn"
encoder1_ffw_type : "FFW"

encoder2_attn_type1 : "ReducedAttn"
encoder2_attn_type2 : "ReducedAttn"
encoder2_ffw_type : "FFW"

encoder3_attn_type1 : "Channel"
encoder3_attn_type2 : "Channel"
encoder3_ffw_type : "GFFW"

# Decoder attention types with FGMA (Flow-Guided Masked Attention)
decoder1_attn_type1 : "Channel"
decoder1_attn_type2 : "FGMA"  # Use FGMA as per paper
decoder1_ffw_type : "GFFW"

decoder2_attn_type1 : "Channel"
decoder2_attn_type2 : "FGMA"
decoder2_ffw_type : "GFFW"

decoder3_attn_type1 : "Channel"
decoder3_attn_type2 : "FGMA"
decoder3_ffw_type : "GFFW"

# Latent attention types
latent_attn_type1 : "FHR"
latent_attn_type2 : "Channel"
latent_attn_type3 : "FHR"
latent_ffw_type : "GFFW"

# Refinement attention types
refinement_attn_type1 : "ReducedAttn"
refinement_attn_type2 : "ReducedAttn"
refinement_ffw_type : "GFFW"

datasets:
  train:
    name: gopro-train
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 192
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: mine-test
    dir_data: ['/hdd2/wrl/zsh/cropped_patches_day/test/']

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]
 
  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: 10000
  save_img: true
  grids: true
  crop_size: 192
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 10000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500


